<?xml version="1.0"?>
<package format="2">
  <name>albc_rl</name>
  <version>1.0.0</version>
  <description>RL student-policy inference node (69D attitude-only, torch-free numpy runtime)</description>

  <maintainer email="nvidia@todo.todo">nvidia</maintainer>

  <license>Apache 2.0</license>

  <buildtool_depend>catkin</buildtool_depend>
  <depend>rospy</depend>
  <depend>std_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>hero_msgs</depend>

</package>
